# App
spring.application.name=schedule-management

# JPA common
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true